// data/staticData.js

const streams = [
  "Computer Science",
  "Electronics & Communication",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Instrumentation Engineering",
];

const topics = {
  "Computer Science": [
    "Data Structures",
    "Algorithms",
    "Database Management",
    "Computer Networks",
    "Operating Systems",
    "Software Engineering",
    "Digital Logic",
    "Computer Architecture",
    "Theory of Computation",
    "Compiler Design",
    "Discrete Mathematics",
    "Linear Algebra",
    "Calculus",
    "Probability & Statistics",
  ],
  "Electronics & Communication": [
    "Analog Circuits",
    "Digital Circuits",
    "Signals & Systems",
    "Control Systems",
    "Communications",
    "Electromagnetics",
    "Electronic Devices",
    "VLSI",
    "Networks",
    "Engineering Mathematics",
  ],
  "Electrical Engineering": [
    "Electric Circuits",
    "Control Systems",
    "Electrical Machines",
    "Power Systems",
    "Power Electronics",
    "Analog Electronics",
    "Digital Electronics",
    "Signals & Systems",
    "Electromagnetic Fields",
    "Measurements",
    "Engineering Mathematics",
  ],
  "Mechanical Engineering": [
    "Engineering Mechanics",
    "Strength of Materials",
    "Theory of Machines",
    "Machine Design",
    "Fluid Mechanics",
    "Heat Transfer",
    "Thermodynamics",
    "Refrigeration and Air Conditioning",
    "Manufacturing Engineering",
    "Industrial Engineering",
    "Engineering Mathematics",
  ],
  "Civil Engineering": [
    "Structural Engineering",
    "Geotechnical Engineering",
    "Water Resources Engineering",
    "Environmental Engineering",
    "Transportation Engineering",
    "Surveying",
    "Construction Materials & Management",
    "Engineering Mechanics",
    "Engineering Mathematics",
  ],
  "Chemical Engineering": [
    "Engineering Mathematics",
    "Process Calculations",
    "Fluid Mechanics",
    "Heat Transfer",
    "Mass Transfer",
    "Chemical Reaction Engineering",
    "Thermodynamics",
    "Instrumentation and Process Control",
    "Plant Design and Economics",
    "Mechanical Operations",
  ],
  "Instrumentation Engineering": [
    "Engineering Mathematics",
    "Electrical Circuits",
    "Signals and Systems",
    "Control Systems",
    "Analog Electronics",
    "Digital Electronics",
    "Measurements",
    "Sensors and Industrial Instrumentation",
    "Communication and Optical Instrumentation",
    "Transducers and Signal Conditioning",
  ],
};
const sampleQuestions = [
  {
    id: 1,
    question:
      "What is the time complexity of searching an element in a balanced binary search tree?",
    options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
    correct: 1,
    explanation:
      "In a balanced BST, the height is log n, so searching takes O(log n) time as we eliminate half the nodes at each level.",
    topic: "Data Structures",
    difficulty: "Medium",
  },
  {
    id: 2,
    question:
      "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort", "Quick Sort", "Merge Sort", "Selection Sort"],
    correct: 2,
    explanation:
      "Merge Sort has a consistent O(n log n) time complexity in all cases, making it optimal for average-case scenarios.",
    topic: "Algorithms",
    difficulty: "Medium",
  },
  {
    id: 3,
    question: "In a relational database, what does ACID stand for?",
    options: [
      "Atomicity, Consistency, Isolation, Durability",
      "Association, Consistency, Integration, Database",
      "Atomicity, Concurrency, Isolation, Database",
      "Association, Concurrency, Integration, Durability",
    ],
    correct: 0,
    explanation:
      "ACID properties ensure reliable database transactions: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent transactions), Durability (permanent changes).",
    topic: "Database Management",
    difficulty: "Easy",
  },
];

export { streams, topics, sampleQuestions };
